"""tools/inventory.py — LangChain tools for inventory operations."""

import uuid
from datetime import datetime, date, timedelta
from typing import Optional
from langchain_core.tools import tool

from data.database import get_db
from data.models import SKU, InventoryRecord, Location, PurchaseOrder, PurchaseOrderLine, UsageHistory


"""tools/inventory.py — LangChain tools for inventory operations."""

import uuid
from datetime import datetime, date, timedelta
from typing import Optional
from langchain_core.tools import tool

from data.database import get_db
from data.models import SKU, InventoryRecord, Location, PurchaseOrder, PurchaseOrderLine, UsageHistory


@tool
def check_stock(
    sku_id: Optional[str] = None,
    location_id: Optional[str] = None,
    category: Optional[str] = None,
    below_par: Optional[str] = None,
) -> str:
    """
    Check current stock levels for one or more SKUs.

    Args:
        sku_id: Specific SKU ID (e.g. 'SKU-00042'). Leave None to query all.
        location_id: Filter by location (e.g. 'LOC-ICU1'). Leave None for all locations.
        category: Filter by category: surgical, pharmaceutical, medical_device, ppe, lab, nutrition, radiology.
        below_par: Pass 'true' to return only items where quantity_on_hand is below reorder_point.

    Returns:
        Summary of stock levels.
    """
    with get_db() as db:
        query = db.query(InventoryRecord, SKU, Location).join(
            SKU, InventoryRecord.sku_id == SKU.id
        ).join(
            Location, InventoryRecord.location_id == Location.id
        )

        if sku_id:
            query = query.filter(InventoryRecord.sku_id == sku_id)
        if location_id:
            query = query.filter(InventoryRecord.location_id == location_id)
        if category:
            query = query.filter(SKU.category == category)
        if below_par and str(below_par).lower() not in ("false", "0", "none", ""):
            query = query.filter(InventoryRecord.quantity_on_hand < SKU.reorder_point)

        results = query.limit(50).all()

        if not results:
            return "No inventory records found matching the criteria."

        lines = []
        for inv, sku, loc in results:
            available = inv.quantity_on_hand - inv.quantity_reserved
            days_cover = round(available / max(1, _avg_daily_usage(db, sku.id, loc.id)), 1)
            status = "🔴 CRITICAL" if inv.quantity_on_hand == 0 else (
                "🟡 LOW" if inv.quantity_on_hand < sku.reorder_point else "🟢 OK"
            )
            lines.append(
                f"{status} | {sku.id} | {sku.name[:40]} | "
                f"Loc: {loc.name} | QoH: {inv.quantity_on_hand} "
                f"(PAR: {sku.reorder_point}) | ~{days_cover}d cover | "
                f"On order: {inv.quantity_on_order}"
            )

        header = f"Stock check — {len(lines)} record(s) returned:\n"
        return header + "\n".join(lines)


@tool
def reorder_item(
    sku_id: str,
    quantity: Optional[int] = None,
    override_supplier_id: Optional[str] = None,
    notes: str = "",
) -> str:
    """
    Create a purchase order (draft) for a SKU.

    Args:
        sku_id: The SKU to reorder.
        quantity: Units to order. If None, uses the SKU's economic order quantity.
        override_supplier_id: Use a different supplier than the default.
        notes: Optional note on the PO.

    Returns:
        Purchase order ID and summary.
    """
    with get_db() as db:
        sku = db.query(SKU).filter(SKU.id == sku_id).first()
        if not sku:
            return f"SKU {sku_id} not found."

        supplier_id = override_supplier_id or sku.supplier_id
        if not supplier_id:
            return f"No supplier configured for {sku_id}."

        qty = quantity or sku.reorder_quantity
        total = qty * sku.unit_cost
        expected = date.today() + timedelta(days=int(sku.lead_time_days * 1.2))

        po_id = f"PO-{datetime.utcnow().strftime('%Y%m%d')}-{uuid.uuid4().hex[:6].upper()}"

        po = PurchaseOrder(
            id=po_id,
            supplier_id=supplier_id,
            expected_delivery=expected,
            total_value=total,
            notes=notes or f"Auto-generated by AI agent for {sku.name}",
        )
        db.add(po)

        line = PurchaseOrderLine(
            po_id=po_id,
            sku_id=sku_id,
            quantity_ordered=qty,
            unit_price=sku.unit_cost,
            line_total=total,
        )
        db.add(line)

        inv_records = db.query(InventoryRecord).filter(InventoryRecord.sku_id == sku_id).all()
        for inv in inv_records:
            inv.quantity_on_order += qty

        return (
            f"✅ PO created: {po_id}\n"
            f"   SKU: {sku_id} — {sku.name}\n"
            f"   Qty: {qty} {sku.unit_of_measure}\n"
            f"   Unit cost: ${sku.unit_cost:.2f} | Total: ${total:,.2f}\n"
            f"   Expected delivery: {expected.isoformat()}\n"
            f"   Status: DRAFT (awaiting approval)"
        )


@tool
def transfer_sku(
    sku_id: str,
    from_location_id: str,
    to_location_id: str,
    quantity: int,
    reason: str = "",
) -> str:
    """
    Transfer stock between locations.

    Args:
        sku_id: SKU to transfer.
        from_location_id: Source location ID.
        to_location_id: Destination location ID.
        quantity: Number of units to transfer.
        reason: Reason for transfer.

    Returns:
        Transfer confirmation or error message.
    """
    with get_db() as db:
        source = db.query(InventoryRecord).filter(
            InventoryRecord.sku_id == sku_id,
            InventoryRecord.location_id == from_location_id
        ).first()

        if not source:
            return f"No stock of {sku_id} found at location {from_location_id}."

        available = source.quantity_on_hand - source.quantity_reserved
        if available < quantity:
            return (
                f"Insufficient stock: {available} units available at {from_location_id}, "
                f"requested {quantity}."
            )

        source.quantity_on_hand -= quantity

        dest = db.query(InventoryRecord).filter(
            InventoryRecord.sku_id == sku_id,
            InventoryRecord.location_id == to_location_id
        ).first()

        if dest:
            dest.quantity_on_hand += quantity
        else:
            dest = InventoryRecord(
                sku_id=sku_id,
                location_id=to_location_id,
                quantity_on_hand=quantity,
            )
            db.add(dest)

        return (
            f"✅ Transfer complete: {quantity} units of {sku_id}\n"
            f"   From: {from_location_id} → To: {to_location_id}\n"
            f"   Reason: {reason or 'Not specified'}\n"
            f"   Remaining at source: {source.quantity_on_hand} units"
        )


@tool
def bulk_update_par_levels(
    category: str,
    adjustment_percent: float,
    location_id: Optional[str] = None,
) -> str:
    """
    Bulk-adjust PAR levels for a category of items.

    Args:
        category: SKU category to adjust.
        adjustment_percent: Percentage change e.g. 20.0 for +20%.
        location_id: Restrict to one location (optional).

    Returns:
        Summary of items updated.
    """
    with get_db() as db:
        skus = db.query(SKU).filter(SKU.category == category).all()

        if not skus:
            return f"No SKUs found in category '{category}'."

        updated = []
        for sku in skus:
            old_par = sku.reorder_point
            new_par = max(1, int(old_par * (1 + adjustment_percent / 100)))
            sku.reorder_point = new_par
            updated.append(f"  {sku.id}: PAR {old_par} → {new_par}")

        return (
            f"✅ Bulk PAR update — {len(updated)} SKUs in '{category}' "
            f"adjusted by {adjustment_percent:+.1f}%:\n" + "\n".join(updated[:20]) +
            (f"\n  ...and {len(updated)-20} more" if len(updated) > 20 else "")
        )


def _avg_daily_usage(db, sku_id: str, location_id: str, days: int = 30) -> float:
    """Compute average daily usage over the past N days."""
    cutoff = date.today() - timedelta(days=days)
    records = db.query(UsageHistory).filter(
        UsageHistory.sku_id == sku_id,
        UsageHistory.location_id == location_id,
        UsageHistory.usage_date >= cutoff,
    ).all()
    if not records:
        return 1.0
    return sum(r.quantity_used for r in records) / days

@tool
def reorder_item(
    sku_id: str,
    quantity: Optional[int] = None,
    override_supplier_id: Optional[str] = None,
    notes: str = "",
) -> str:
    """
    Create a purchase order (draft) for a SKU.

    Args:
        sku_id: The SKU to reorder.
        quantity: Units to order. If None, uses the SKU's economic order quantity.
        override_supplier_id: Use a different supplier than the default.
        notes: Optional note on the PO (reason, urgency, etc.).

    Returns:
        Purchase order ID and summary.
    """
    with get_db() as db:
        sku = db.query(SKU).filter(SKU.id == sku_id).first()
        if not sku:
            return f"SKU {sku_id} not found."

        supplier_id = override_supplier_id or sku.supplier_id
        if not supplier_id:
            return f"No supplier configured for {sku_id}. Please assign a supplier first."

        qty = quantity or sku.reorder_quantity
        total = qty * sku.unit_cost
        expected = date.today() + timedelta(days=int(sku.lead_time_days * 1.2))

        po_id = f"PO-{datetime.utcnow().strftime('%Y%m%d')}-{uuid.uuid4().hex[:6].upper()}"

        po = PurchaseOrder(
            id=po_id,
            supplier_id=supplier_id,
            expected_delivery=expected,
            total_value=total,
            notes=notes or f"Auto-generated by AI agent for {sku.name}",
        )
        db.add(po)

        line = PurchaseOrderLine(
            po_id=po_id,
            sku_id=sku_id,
            quantity_ordered=qty,
            unit_price=sku.unit_cost,
            line_total=total,
        )
        db.add(line)

        # Update quantity on order
        inv_records = db.query(InventoryRecord).filter(InventoryRecord.sku_id == sku_id).all()
        for inv in inv_records:
            inv.quantity_on_order += qty

        return (
            f"✅ PO created: {po_id}\n"
            f"   SKU: {sku_id} — {sku.name}\n"
            f"   Qty: {qty} {sku.unit_of_measure}\n"
            f"   Unit cost: ${sku.unit_cost:.2f} | Total: ${total:,.2f}\n"
            f"   Expected delivery: {expected.isoformat()}\n"
            f"   Status: DRAFT (awaiting approval)"
        )


@tool
def transfer_sku(
    sku_id: str,
    from_location_id: str,
    to_location_id: str,
    quantity: int,
    reason: str = "",
) -> str:
    """
    Transfer stock between locations (e.g. central supply → ICU-2).

    Args:
        sku_id: SKU to transfer.
        from_location_id: Source location ID.
        to_location_id: Destination location ID.
        quantity: Number of units to transfer.
        reason: Reason for transfer (optional).

    Returns:
        Transfer confirmation or error message.
    """
    with get_db() as db:
        source = db.query(InventoryRecord).filter(
            InventoryRecord.sku_id == sku_id,
            InventoryRecord.location_id == from_location_id
        ).first()

        if not source:
            return f"No stock of {sku_id} found at location {from_location_id}."

        available = source.quantity_on_hand - source.quantity_reserved
        if available < quantity:
            return (
                f"Insufficient stock: {available} units available at {from_location_id}, "
                f"requested {quantity}."
            )

        # Deduct from source
        source.quantity_on_hand -= quantity

        # Add to destination (create record if needed)
        dest = db.query(InventoryRecord).filter(
            InventoryRecord.sku_id == sku_id,
            InventoryRecord.location_id == to_location_id
        ).first()

        if dest:
            dest.quantity_on_hand += quantity
        else:
            dest = InventoryRecord(
                sku_id=sku_id,
                location_id=to_location_id,
                quantity_on_hand=quantity,
            )
            db.add(dest)

        return (
            f"✅ Transfer complete: {quantity} units of {sku_id}\n"
            f"   From: {from_location_id} → To: {to_location_id}\n"
            f"   Reason: {reason or 'Not specified'}\n"
            f"   Remaining at source: {source.quantity_on_hand} units"
        )


@tool
def bulk_update_par_levels(
    category: str,
    adjustment_percent: float,
    location_id: Optional[str] = None,
) -> str:
    """
    Bulk-adjust PAR levels for a category of items (e.g. increase PPE PAR by 20%).

    Args:
        category: SKU category to adjust.
        adjustment_percent: Percentage change, e.g. 20.0 for +20%, -10.0 for -10%.
        location_id: Restrict to one location (optional).

    Returns:
        Summary of items updated.
    """
    with get_db() as db:
        query = db.query(SKU).filter(SKU.category == category)
        skus = query.all()

        if not skus:
            return f"No SKUs found in category '{category}'."

        updated = []
        for sku in skus:
            old_par = sku.reorder_point
            new_par = max(1, int(old_par * (1 + adjustment_percent / 100)))
            sku.reorder_point = new_par
            updated.append(f"  {sku.id}: PAR {old_par} → {new_par}")

        return (
            f"✅ Bulk PAR update — {len(updated)} SKUs in '{category}' "
            f"adjusted by {adjustment_percent:+.1f}%:\n" + "\n".join(updated[:20]) +
            (f"\n  ...and {len(updated)-20} more" if len(updated) > 20 else "")
        )


# ── Internal helper ────────────────────────────────────────────────────────────

def _avg_daily_usage(db, sku_id: str, location_id: str, days: int = 30) -> float:
    """Compute average daily usage over the past N days."""
    cutoff = date.today() - timedelta(days=days)
    records = db.query(UsageHistory).filter(
        UsageHistory.sku_id == sku_id,
        UsageHistory.location_id == location_id,
        UsageHistory.usage_date >= cutoff,
    ).all()
    if not records:
        return 1.0  # Assume 1 unit/day if no history
    return sum(r.quantity_used for r in records) / days
